// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeaESBjbJ5wsP1aS8ukyL5q_AzO3ujcbU',
    appId: '1:609028318663:web:5cdf3fd4131c547e8ba5e2',
    messagingSenderId: '609028318663',
    projectId: 'bengala-fc-f93fa',
    authDomain: 'bengala-fc-f93fa.firebaseapp.com',
    storageBucket: 'bengala-fc-f93fa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTuGmuKabqC3wwnK-0N-uFqQSZxJ69OLo',
    appId: '1:609028318663:android:9f8b5a95ab562da78ba5e2',
    messagingSenderId: '609028318663',
    projectId: 'bengala-fc-f93fa',
    storageBucket: 'bengala-fc-f93fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9eHASB-Q8pT3fo7VTwMe1qrx64kWZUDE',
    appId: '1:609028318663:ios:f6e8bf3ef7a273f78ba5e2',
    messagingSenderId: '609028318663',
    projectId: 'bengala-fc-f93fa',
    storageBucket: 'bengala-fc-f93fa.firebasestorage.app',
    iosBundleId: 'com.example.bengalafc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9eHASB-Q8pT3fo7VTwMe1qrx64kWZUDE',
    appId: '1:609028318663:ios:f6e8bf3ef7a273f78ba5e2',
    messagingSenderId: '609028318663',
    projectId: 'bengala-fc-f93fa',
    storageBucket: 'bengala-fc-f93fa.firebasestorage.app',
    iosBundleId: 'com.example.bengalafc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeaESBjbJ5wsP1aS8ukyL5q_AzO3ujcbU',
    appId: '1:609028318663:web:3cfdb51527e833708ba5e2',
    messagingSenderId: '609028318663',
    projectId: 'bengala-fc-f93fa',
    authDomain: 'bengala-fc-f93fa.firebaseapp.com',
    storageBucket: 'bengala-fc-f93fa.firebasestorage.app',
  );
}
